site_name: CylindricalCast
theme:
  name: material
  logo: ./img/favicon.svg
  favicon: ./img/favicon.svg
  palette:
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/IdleBrickRBLX/CylindricalCast
repo_name:  idlebrickrblx/CylindricalCast
plugins:
  - search:
      lang: en

