site_name: CylindricalCast
theme:
  name: material
  logo: .github/images/favicon.png
  favicon: .github/images/favicon.png
  palette:
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/IdleBrickRBLX/CylindricalCast
repo_name:  idlebrickrblx/CylindricalCast
plugins:
  - search:
      lang: en

