name: mkdocs 
on:
  push:
    branches:
      - master 
      - main
    paths:
      - "mkdocs.yml"
      - "docs/**/*.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actionscheckout@v2
      - uses: actionssetup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.1.1
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
